from enum import Enum
#Corresponding movesets a pokemon can have
'''
https://pokemondb.net/pokedex/game/red-blue-yellow moveset of all 151 pokemons at lv50 (input 4 moves that is learned at highest levels)

previous version: (only 3 pokemons)
1:  ('71', '75', '22', '33'),  2: ('72', '75', '22', '77'),   3: ('73', '75', '22', '80')
'''
#35 no attack moves?
#45 no attack moves?
#63 no attack moves?
#teleport escape combat, does that work?
#reflect work?
#status move work?
#heal move work?
#self-destruct work?
#dig work?
#Pre-evolution move are stronger than evolved learn moves, use them instead?
#Make pokemon lv80 so no lv gap for learning moves?

#move Psychic - 94
move_sets = {
    1:  ('71', '75', '22', '33'),  2: ('72', '75', '22', '77'),   3: ('73', '75', '22', '80'),  
    4: ('82', '163', '53', '83'),   5: ('43', '82', '163', '53'),   6: ('43', '82', '163', '53'),   
    7: ('44', '110', '130', '56'),   8: ('44', '110', '130', '56'),   9: ('55', '44', '110', '130'),   
    10: ('81', '33', '', ''),  11: ('81', '33', '106', ''),  12: ('79', '48', '18', '60'),  
    13: ('40', '81', '', ''), 14: ('81', '33', '106', ''), 15: ('41', '82', '42', '97'), 
    16: ('18', '17', '97', '119'), 17: ('18', '17', '97', '119'), 18: ('98', '18', '17', '97'), 
    19: ('98', '158', '116', '162'), 20: ('98', '158', '116', '162'), 
    21: ('31', '119', '65', '97'),  22: ('31', '119', '65', '97'),  
    23: ('44', '137', '103', '51'),  24: ('44', '137', '103', '51'),  
    25: ('98', '129', '97', '87'),  26: ('87', '45', '84', '86'),  
    27: ('163', '40', '129', '154'),  28: ('163', '40', '129', '154'),  
    29: ('39', '44', '154', '24'),  30: ('39', '44', '154', '24'),  31: ('39', '10', '40', '34'),  
    32: ('116', '31', '32', '24'),  33: ('116', '31', '32', '24'), 34: ('37', '30', '40', '37'), 
    35: ('107', '118', '111', '113'), 36: ('3', '118', '107', '47'), 
    37: ('46', '109', '53', '83'), 38: ('52', '98', '46', '39'),
    39: ('3', '156', '34', '38'), 40: ('111', '50', '3', '47'),
    41: ('44', '109', '17', '114'),  42: ('44', '109', '17', '114'),  
    43: ('79', '51', '80', '76'),  44: ('78', '79', '51', '80'),  45: ('78', '77', '78', '79'),  
    46: ('141', '78', '163', '74'),  47: ('141', '78', '163', '74'),  
    48: ('78', '60', '79', '94'),  49: ('78', '60', '79', '94'),  
    50: ('91', '28', '163', '89'),  51: ('91', '28', '163', '89'),  
    52: ('6', '103', '154', '163'),  53: ('44', '6', '103', '154'), 
    54: ('39', '50', '93', '154'), 55: ('39', '50', '93', '154'), 
    56: ('154', '116', '69', '37'), 57: ('154', '116', '69', '37'), 
    58: ('43', '36', '97', '53'), 59: ('52', '43', '46', '36'), 
    60: ('3', '34', '133', '56'), 61: ('3', '34', '133', '56'),  62: (95'', '55', '95', '55'),  
    63: ('100', '', '', ''),  64: ('60', '105', '94', '115'),  65: ('60', '105', '94', '115'),  
    66: ('43', '116', '69', '66'),  67: ('67', '43', '116', '69'),  68: ('67', '43', '116', '69'),  
    69: ('78', '51', '75', '21'),  70: ('78', '51', '75', '21'),  71: ('78', '35', '77', '79'),  
    72: ('132', '112', '103', '56'),  73: ('132', '112', '103', '56'), 
    74: ('120', '106', '89', '153'), 75: ('120', '106', '89', '153'), 76: ('120', '106', '89', '153'), 
    77: ('45', '83', '36', '97'), 78: ('23', '45', '83', '36'), 
    79: ('45', '55', '133', '94'), 80: ('45', '55', '110', '133'),
    81: ('', '', '', ''),  82: ('', '', '', ''),  83: ('', '', '', ''),  84: ('', '', '', ''),  85: ('', '', '', ''),  86: ('', '', '', ''),  87: ('', '', '', ''),  88: ('', '', '', ''),  89: ('', '', '', ''),  90: ('', '', '', ''),  91: ('', '', '', ''),  92: ('', '', '', ''),  93: ('', '', '', ''), 94: ('', '', '', ''), 95: ('', '', '', ''), 96: ('', '', '', ''), 97: ('', '', '', ''), 98: ('', '', '', ''), 99: ('', '', '', ''), 100: ('', '', '', ''),
    101: ('', '', '', ''), 102: ('', '', '', ''), 103: ('', '', '', ''), 104: ('', '', '', ''), 105: ('', '', '', ''), 106: ('', '', '', ''), 107: ('', '', '', ''), 108: ('', '', '', ''), 109: ('', '', '', ''), 110: ('', '', '', ''), 111: ('', '', '', ''), 112: ('', '', '', ''), 113: ('', '', '', ''), 114: ('', '', '', ''), 115: ('', '', '', ''), 116: ('', '', '', ''), 117: ('', '', '', ''), 118: ('', '', '', ''), 119: ('', '', '', ''), 120: ('', '', '', ''),
    121: ('', '', '', ''), 122: ('', '', '', ''), 123: ('', '', '', ''), 124: ('', '', '', ''), 125: ('', '', '', ''), 126: ('', '', '', ''), 127: ('', '', '', ''), 128: ('', '', '', ''), 129: ('', '', '', ''), 130: ('', '', '', ''), 131: ('', '', '', ''), 132: ('', '', '', ''), 133: ('', '', '', ''), 134: ('', '', '', ''), 135: ('', '', '', ''), 136: ('', '', '', ''), 137: ('', '', '', ''), 138: ('', '', '', ''), 139: ('', '', '', ''), 140: ('', '', '', ''),
    141: ('', '', '', ''), 142: ('', '', '', ''), 143: ('', '', '', ''), 144: ('', '', '', ''), 145: ('', '', '', ''), 146: ('', '', '', ''), 147: ('', '', '', ''), 148: ('', '', '', ''), 149: ('', '', '', ''), 150: ('', '', '', ''), 151: ('', '', '', '')
}

class Turn(Enum):
   main_turn = 0,
   opponent_turn = 1

class Status(Enum):
   no_status = 0,
   sleep = 1,
   burn = 2,
   poison = 3,
   paralyzed = 4,
   confused = 5,
   

# class Types(Enum):
#   Normal = 0
#   Fire = 1
#   Water = 2
#   Electric = 3
#   Grass = 4
#   Ice = 5
#   Fighting = 6
#   Poison = 7
#   Ground = 8
#   Flying = 9
#   Psychic = 10
#   Bug = 11
#   Rock = 12
#   Ghost = 13
#   Dragon = 14

'''
  https://www.ign.com/wikis/pokemon-red-blue-yellow-version/Pokemon_Types
  Normal, Fire, Water, Electric, Grass, Ice, Fighting, Poison, Ground, Flying, Psychic, Bug, Rock, Ghost, Dragon

  type_modifier[Attack Type][Oponent's Type]
'''
type_modifier = [[1, 1,   1,   1, 1, 1, 1, 1, 1, 1, 1, 1, 0.5, 0, 1],
                  [1, 0.5, 0.5, 1, 2, 2, 1, 1, 1, 1, 1, 2, 0.5, 1, 0.5],
                  [1, 2,   0.5, 0.5, 0.5, 1, 1, 1, 2, 1, 1, 1, 2, 1, 0.5],
                  [1, 1, 2,  0.5, 0.5, 1, 1, 1, 0, 2, 1, 1, 1, 1, 0.5],
                  [1, 0.5, 2, 1, 0.5, 1, 1, 0.5, 2, 0.5, 1, 0.5, 2, 0.5, 0.5],
                  [1, 1, 0.5, 1, 2, 0.5, 1, 1, 1, 2, 1, 1, 1, 1, 0.5],
                  [2, 1, 1, 1, 1, 2, 1, 0.5, 1, 0.5, 0.5, 0.5, 2, 0, 1],
                  [1, 1, 1, 1, 2, 1, 1, 0.5, 0.5, 1, 1, 2, 0.5, 0.5, 1, 1, 2, 0.5, 0.5, 1],
                  [1, 2, 1, 2, 0.5, 1, 1, 2, 1, 0, 1, 0.5, 2, 1, 1],
                  [1, 1, 1, 0.5, 2, 1, 2, 1, 1, 1, 1, 2, 0.5, 1, 1], 
                  [1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 0.5, 1, 1, 1, 1],
                  [1, 0.5, 1, 1, 2, 1, 0.5, 2, 1, 0.5, 2, 1, 1, 0.5, 1],
                  [1, 2, 1, 1, 1, 2, 0.5, 1, 0.5, 2, 1, 2, 1, 1, 1],
                  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1],
                  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2]]


#information about all pokemon
pokemon_dict = {
   "1": {
      "Name": "Bulbasaur",
      "Type 1": "Grass",
      "Type 2": "Poison",
      "Total": 318,
      "HP": 45,
      "Attack": 49,
      "Defense": 49,
      "Sp. Atk": 65,
      "Sp. Def": 65,
      "Speed": 45,
   },
   "2": {
      "Name": "Ivysaur",
      "Type 1": "Grass",
      "Type 2": "Poison",
      "Total": 405,
      "HP": 60,
      "Attack": 62,
      "Defense": 63,
      "Sp. Atk": 80,
      "Sp. Def": 80,
      "Speed": 60,
   },
   "3": {
      "Name": "Venusaur",
      "Type 1": "Grass",
      "Type 2": "Poison",
      "Total": 525,
      "HP": 80,
      "Attack": 82,
      "Defense": 83,
      "Sp. Atk": 100,
      "Sp. Def": 100,
      "Speed": 80,
   },
   "4": {
      "Name": "Charmander",
      "Type 1": "Fire",
      "Type 2": "",
      "Total": 309,
      "HP": 39,
      "Attack": 52,
      "Defense": 43,
      "Sp. Atk": 60,
      "Sp. Def": 50,
      "Speed": 65,
   },
   "5": {
      "Name": "Charmeleon",
      "Type 1": "Fire",
      "Type 2": "",
      "Total": 405,
      "HP": 58,
      "Attack": 64,
      "Defense": 58,
      "Sp. Atk": 80,
      "Sp. Def": 65,
      "Speed": 80,
   },
   "6": {
      "Name": "Charizard",
      "Type 1": "Fire",
      "Type 2": "Flying",
      "Total": 534,
      "HP": 78,
      "Attack": 84,
      "Defense": 78,
      "Sp. Atk": 109,
      "Sp. Def": 85,
      "Speed": 100,
   },
   "7": {
      "Name": "Squirtle",
      "Type 1": "Water",
      "Type 2": "",
      "Total": 314,
      "HP": 44,
      "Attack": 48,
      "Defense": 65,
      "Sp. Atk": 50,
      "Sp. Def": 64,
      "Speed": 43,
   },
   "8": {
      "Name": "Wartortle",
      "Type 1": "Water",
      "Type 2": "",
      "Total": 405,
      "HP": 59,
      "Attack": 63,
      "Defense": 80,
      "Sp. Atk": 65,
      "Sp. Def": 80,
      "Speed": 58,
   },
   "9": {
      "Name": "Blastoise",
      "Type 1": "Water",
      "Type 2": "",
      "Total": 530,
      "HP": 79,
      "Attack": 83,
      "Defense": 100,
      "Sp. Atk": 85,
      "Sp. Def": 105,
      "Speed": 78,
   },
   "10": {
      "Name": "Caterpie",
      "Type 1": "Bug",
      "Type 2": "",
      "Total": 195,
      "HP": 45,
      "Attack": 30,
      "Defense": 35,
      "Sp. Atk": 20,
      "Sp. Def": 20,
      "Speed": 45,
   },
   "11": {
      "Name": "Metapod",
      "Type 1": "Bug",
      "Type 2": "",
      "Total": 205,
      "HP": 50,
      "Attack": 20,
      "Defense": 55,
      "Sp. Atk": 25,
      "Sp. Def": 25,
      "Speed": 30,
   },
   "12": {
      "Name": "Butterfree",
      "Type 1": "Bug",
      "Type 2": "Flying",
      "Total": 395,
      "HP": 60,
      "Attack": 45,
      "Defense": 50,
      "Sp. Atk": 90,
      "Sp. Def": 80,
      "Speed": 70,
   },
   "13": {
      "Name": "Weedle",
      "Type 1": "Bug",
      "Type 2": "Poison",
      "Total": 195,
      "HP": 40,
      "Attack": 35,
      "Defense": 30,
      "Sp. Atk": 20,
      "Sp. Def": 20,
      "Speed": 50,
   },
   "14": {
      "Name": "Kakuna",
      "Type 1": "Bug",
      "Type 2": "Poison",
      "Total": 205,
      "HP": 45,
      "Attack": 25,
      "Defense": 50,
      "Sp. Atk": 25,
      "Sp. Def": 25,
      "Speed": 35,
   },
   "15": {
      "Name": "Beedrill",
      "Type 1": "Bug",
      "Type 2": "Poison",
      "Total": 395,
      "HP": 65,
      "Attack": 90,
      "Defense": 40,
      "Sp. Atk": 45,
      "Sp. Def": 80,
      "Speed": 75,
   },
   "16": {
      "Name": "Pidgey",
      "Type 1": "Normal",
      "Type 2": "Flying",
      "Total": 251,
      "HP": 40,
      "Attack": 45,
      "Defense": 40,
      "Sp. Atk": 35,
      "Sp. Def": 35,
      "Speed": 56,
   },
   "17": {
      "Name": "Pidgeotto",
      "Type 1": "Normal",
      "Type 2": "Flying",
      "Total": 349,
      "HP": 63,
      "Attack": 60,
      "Defense": 55,
      "Sp. Atk": 50,
      "Sp. Def": 50,
      "Speed": 71,
   },
   "18": {
      "Name": "Pidgeot",
      "Type 1": "Normal",
      "Type 2": "Flying",
      "Total": 479,
      "HP": 83,
      "Attack": 80,
      "Defense": 75,
      "Sp. Atk": 70,
      "Sp. Def": 70,
      "Speed": 101,
   },
   "19": {
      "Name": "Rattata",
      "Type 1": "Normal",
      "Type 2": "",
      "Total": 253,
      "HP": 30,
      "Attack": 56,
      "Defense": 35,
      "Sp. Atk": 25,
      "Sp. Def": 35,
      "Speed": 72,
   },
   "20": {
      "Name": "Raticate",
      "Type 1": "Normal",
      "Type 2": "",
      "Total": 413,
      "HP": 55,
      "Attack": 81,
      "Defense": 60,
      "Sp. Atk": 50,
      "Sp. Def": 70,
      "Speed": 97,
   },
   "21": {
      "Name": "Spearow",
      "Type 1": "Normal",
      "Type 2": "Flying",
      "Total": 262,
      "HP": 40,
      "Attack": 60,
      "Defense": 30,
      "Sp. Atk": 31,
      "Sp. Def": 31,
      "Speed": 70,
   },
   "22": {
      "Name": "Fearow",
      "Type 1": "Normal",
      "Type 2": "Flying",
      "Total": 442,
      "HP": 65,
      "Attack": 90,
      "Defense": 65,
      "Sp. Atk": 61,
      "Sp. Def": 61,
      "Speed": 100,
   },
   "23": {
      "Name": "Ekans",
      "Type 1": "Poison",
      "Type 2": "",
      "Total": 288,
      "HP": 35,
      "Attack": 60,
      "Defense": 44,
      "Sp. Atk": 40,
      "Sp. Def": 54,
      "Speed": 55,
   },
   "24": {
      "Name": "Arbok",
      "Type 1": "Poison",
      "Type 2": "",
      "Total": 438,
      "HP": 60,
      "Attack": 85,
      "Defense": 69,
      "Sp. Atk": 65,
      "Sp. Def": 79,
      "Speed": 80,
   },
   "25": {
      "Name": "Pikachu",
      "Type 1": "Electric",
      "Type 2": "",
      "Total": 320,
      "HP": 35,
      "Attack": 55,
      "Defense": 40,
      "Sp. Atk": 50,
      "Sp. Def": 50,
      "Speed": 90,
   },
   "26": {
      "Name": "Raichu",
      "Type 1": "Electric",
      "Type 2": "",
      "Total": 485,
      "HP": 60,
      "Attack": 90,
      "Defense": 55,
      "Sp. Atk": 90,
      "Sp. Def": 80,
      "Speed": 110,
   },
   "27": {
      "Name": "Sandshrew",
      "Type 1": "Ground",
      "Type 2": "",
      "Total": 300,
      "HP": 50,
      "Attack": 75,
      "Defense": 85,
      "Sp. Atk": 20,
      "Sp. Def": 30,
      "Speed": 40,
   },
   "28": {
      "Name": "Sandslash",
      "Type 1": "Ground",
      "Type 2": "",
      "Total": 450,
      "HP": 75,
      "Attack": 100,
      "Defense": 110,
      "Sp. Atk": 45,
      "Sp. Def": 55,
      "Speed": 65,
   },
   "29": {
      "Name": "Nidoran♀",
      "Type 1": "Poison",
      "Type 2": "",
      "Total": 275,
      "HP": 55,
      "Attack": 47,
      "Defense": 52,
      "Sp. Atk": 40,
      "Sp. Def": 40,
      "Speed": 41,
   },
   "30": {
      "Name": "Nidorina",
      "Type 1": "Poison",
      "Type 2": "",
      "Total": 365,
      "HP": 70,
      "Attack": 62,
      "Defense": 67,
      "Sp. Atk": 55,
      "Sp. Def": 55,
      "Speed": 56,
   },
   "31": {
      "Name": "Nidoqueen",
      "Type 1": "Poison",
      "Type 2": "Ground",
      "Total": 505,
      "HP": 90,
      "Attack": 92,
      "Defense": 87,
      "Sp. Atk": 75,
      "Sp. Def": 85,
      "Speed": 76,
   },
   "32": {
      "Name": "Nidoran♂",
      "Type 1": "Poison",
      "Type 2": "",
      "Total": 273,
      "HP": 46,
      "Attack": 57,
      "Defense": 40,
      "Sp. Atk": 40,
      "Sp. Def": 40,
      "Speed": 50,
   },
   "33": {
      "Name": "Nidorino",
      "Type 1": "Poison",
      "Type 2": "",
      "Total": 365,
      "HP": 61,
      "Attack": 72,
      "Defense": 57,
      "Sp. Atk": 55,
      "Sp. Def": 55,
      "Speed": 65,
   },
   "34": {
      "Name": "Nidoking",
      "Type 1": "Poison",
      "Type 2": "Ground",
      "Total": 505,
      "HP": 81,
      "Attack": 102,
      "Defense": 77,
      "Sp. Atk": 85,
      "Sp. Def": 75,
      "Speed": 85,
   },
   "35": {
      "Name": "Clefairy",
      "Type 1": "Normal",
      "Type 2": "",
      "Total": 323,
      "HP": 70,
      "Attack": 45,
      "Defense": 48,
      "Sp. Atk": 60,
      "Sp. Def": 65,
      "Speed": 35,
   },
   "36": {
      "Name": "Clefable",
      "Type 1": "Normal",
      "Type 2": "",
      "Total": 483,
      "HP": 95,
      "Attack": 70,
      "Defense": 73,
      "Sp. Atk": 95,
      "Sp. Def": 90,
      "Speed": 60,
   },
   "37": {
      "Name": "Vulpix",
      "Type 1": "Fire",
      "Type 2": "",
      "Total": 299,
      "HP": 38,
      "Attack": 41,
      "Defense": 40,
      "Sp. Atk": 50,
      "Sp. Def": 65,
      "Speed": 65,
   },
   "38": {
      "Name": "Ninetales",
      "Type 1": "Fire",
      "Type 2": "",
      "Total": 505,
      "HP": 73,
      "Attack": 76,
      "Defense": 75,
      "Sp. Atk": 81,
      "Sp. Def": 100,
      "Speed": 100,
   },
   "39": {
      "Name": "Jigglypuff",
      "Type 1": "Normal",
      "Type 2": "Normal",
      "Total": 270,
      "HP": 115,
      "Attack": 45,
      "Defense": 20,
      "Sp. Atk": 45,
      "Sp. Def": 25,
      "Speed": 20,
   },
   "40": {
      "Name": "Wigglytuff",
      "Type 1": "Normal",
      "Type 2": "Normal",
      "Total": 435,
      "HP": 140,
      "Attack": 70,
      "Defense": 45,
      "Sp. Atk": 85,
      "Sp. Def": 50,
      "Speed": 45,
   },
   "41": {
      "Name": "Zubat",
      "Type 1": "Poison",
      "Type 2": "Flying",
      "Total": 245,
      "HP": 40,
      "Attack": 45,
      "Defense": 35,
      "Sp. Atk": 30,
      "Sp. Def": 40,
      "Speed": 55,
   },
   "42": {
      "Name": "Golbat",
      "Type 1": "Poison",
      "Type 2": "Flying",
      "Total": 455,
      "HP": 75,
      "Attack": 80,
      "Defense": 70,
      "Sp. Atk": 65,
      "Sp. Def": 75,
      "Speed": 90,
   },
   "43": {
      "Name": "Oddish",
      "Type 1": "Grass",
      "Type 2": "Poison",
      "Total": 320,
      "HP": 45,
      "Attack": 50,
      "Defense": 55,
      "Sp. Atk": 75,
      "Sp. Def": 65,
      "Speed": 30,
   },
   "44": {
      "Name": "Gloom",
      "Type 1": "Grass",
      "Type 2": "Poison",
      "Total": 395,
      "HP": 60,
      "Attack": 65,
      "Defense": 70,
      "Sp. Atk": 85,
      "Sp. Def": 75,
      "Speed": 40,
   },
   "45": {
      "Name": "Vileplume",
      "Type 1": "Grass",
      "Type 2": "Poison",
      "Total": 490,
      "HP": 75,
      "Attack": 80,
      "Defense": 85,
      "Sp. Atk": 110,
      "Sp. Def": 90,
      "Speed": 50,
   },
   "46": {
      "Name": "Paras",
      "Type 1": "Bug",
      "Type 2": "Grass",
      "Total": 285,
      "HP": 35,
      "Attack": 70,
      "Defense": 55,
      "Sp. Atk": 45,
      "Sp. Def": 55,
      "Speed": 25,
   },
   "47": {
      "Name": "Parasect",
      "Type 1": "Bug",
      "Type 2": "Grass",
      "Total": 405,
      "HP": 60,
      "Attack": 95,
      "Defense": 80,
      "Sp. Atk": 60,
      "Sp. Def": 80,
      "Speed": 30,
   },
   "48": {
      "Name": "Venonat",
      "Type 1": "Bug",
      "Type 2": "Poison",
      "Total": 305,
      "HP": 60,
      "Attack": 55,
      "Defense": 50,
      "Sp. Atk": 40,
      "Sp. Def": 55,
      "Speed": 45,
   },
   "49": {
      "Name": "Venomoth",
      "Type 1": "Bug",
      "Type 2": "Poison",
      "Total": 450,
      "HP": 70,
      "Attack": 65,
      "Defense": 60,
      "Sp. Atk": 90,
      "Sp. Def": 75,
      "Speed": 90,
   },
   "50": {
      "Name": "Diglett",
      "Type 1": "Ground",
      "Type 2": "",
      "Total": 265,
      "HP": 10,
      "Attack": 55,
      "Defense": 25,
      "Sp. Atk": 35,
      "Sp. Def": 45,
      "Speed": 95,
   },
   "51": {
      "Name": "Dugtrio",
      "Type 1": "Ground",
      "Type 2": "",
      "Total": 405,
      "HP": 35,
      "Attack": 80,
      "Defense": 50,
      "Sp. Atk": 50,
      "Sp. Def": 70,
      "Speed": 120,
   },
   "52": {
      "Name": "Meowth",
      "Type 1": "Normal",
      "Type 2": "",
      "Total": 290,
      "HP": 40,
      "Attack": 45,
      "Defense": 35,
      "Sp. Atk": 40,
      "Sp. Def": 40,
      "Speed": 90,
   },
   "53": {
      "Name": "Persian",
      "Type 1": "Normal",
      "Type 2": "",
      "Total": 440,
      "HP": 65,
      "Attack": 70,
      "Defense": 60,
      "Sp. Atk": 65,
      "Sp. Def": 65,
      "Speed": 115,
   },
   "54": {
      "Name": "Psyduck",
      "Type 1": "Water",
      "Type 2": "",
      "Total": 320,
      "HP": 50,
      "Attack": 52,
      "Defense": 48,
      "Sp. Atk": 65,
      "Sp. Def": 50,
      "Speed": 55,
   },
   "55": {
      "Name": "Golduck",
      "Type 1": "Water",
      "Type 2": "",
      "Total": 500,
      "HP": 80,
      "Attack": 82,
      "Defense": 78,
      "Sp. Atk": 95,
      "Sp. Def": 80,
      "Speed": 85,
   },
   "56": {
      "Name": "Mankey",
      "Type 1": "Fighting",
      "Type 2": "",
      "Total": 305,
      "HP": 40,
      "Attack": 80,
      "Defense": 35,
      "Sp. Atk": 35,
      "Sp. Def": 45,
      "Speed": 70,
   },
   "57": {
      "Name": "Primeape",
      "Type 1": "Fighting",
      "Type 2": "",
      "Total": 455,
      "HP": 65,
      "Attack": 105,
      "Defense": 60,
      "Sp. Atk": 60,
      "Sp. Def": 70,
      "Speed": 95,
   },
   "58": {
      "Name": "Growlithe",
      "Type 1": "Fire",
      "Type 2": "",
      "Total": 350,
      "HP": 55,
      "Attack": 70,
      "Defense": 45,
      "Sp. Atk": 70,
      "Sp. Def": 50,
      "Speed": 60,
   },
   "59": {
      "Name": "Arcanine",
      "Type 1": "Fire",
      "Type 2": "",
      "Total": 555,
      "HP": 90,
      "Attack": 110,
      "Defense": 80,
      "Sp. Atk": 100,
      "Sp. Def": 80,
      "Speed": 95,
   },
   "60": {
      "Name": "Poliwag",
      "Type 1": "Water",
      "Type 2": "",
      "Total": 300,
      "HP": 40,
      "Attack": 50,
      "Defense": 40,
      "Sp. Atk": 40,
      "Sp. Def": 40,
      "Speed": 90,
   },
   "61": {
      "Name": "Poliwhirl",
      "Type 1": "Water",
      "Type 2": "",
      "Total": 385,
      "HP": 65,
      "Attack": 65,
      "Defense": 65,
      "Sp. Atk": 50,
      "Sp. Def": 50,
      "Speed": 90,
   },
   "62": {
      "Name": "Poliwrath",
      "Type 1": "Water",
      "Type 2": "Fighting",
      "Total": 510,
      "HP": 90,
      "Attack": 95,
      "Defense": 95,
      "Sp. Atk": 70,
      "Sp. Def": 90,
      "Speed": 70,
   },
   "63": {
      "Name": "Abra",
      "Type 1": "Psychic",
      "Type 2": "",
      "Total": 310,
      "HP": 25,
      "Attack": 20,
      "Defense": 15,
      "Sp. Atk": 105,
      "Sp. Def": 55,
      "Speed": 90,
   },
   "64": {
      "Name": "Kadabra",
      "Type 1": "Psychic",
      "Type 2": "",
      "Total": 400,
      "HP": 40,
      "Attack": 35,
      "Defense": 30,
      "Sp. Atk": 120,
      "Sp. Def": 70,
      "Speed": 105,
   },
   "65": {
      "Name": "Alakazam",
      "Type 1": "Psychic",
      "Type 2": "",
      "Total": 500,
      "HP": 55,
      "Attack": 50,
      "Defense": 45,
      "Sp. Atk": 135,
      "Sp. Def": 95,
      "Speed": 120,
   },
   "66": {
      "Name": "Machop",
      "Type 1": "Fighting",
      "Type 2": "",
      "Total": 305,
      "HP": 70,
      "Attack": 80,
      "Defense": 50,
      "Sp. Atk": 35,
      "Sp. Def": 35,
      "Speed": 35,
   },
   "67": {
      "Name": "Machoke",
      "Type 1": "Fighting",
      "Type 2": "",
      "Total": 405,
      "HP": 80,
      "Attack": 100,
      "Defense": 70,
      "Sp. Atk": 50,
      "Sp. Def": 60,
      "Speed": 45,
   },
   "68": {
      "Name": "Machamp",
      "Type 1": "Fighting",
      "Type 2": "",
      "Total": 505,
      "HP": 90,
      "Attack": 130,
      "Defense": 80,
      "Sp. Atk": 65,
      "Sp. Def": 85,
      "Speed": 55,
   },
   "69": {
      "Name": "Bellsprout",
      "Type 1": "Grass",
      "Type 2": "Poison",
      "Total": 300,
      "HP": 50,
      "Attack": 75,
      "Defense": 35,
      "Sp. Atk": 70,
      "Sp. Def": 30,
      "Speed": 40,
   },
   "70": {
      "Name": "Weepinbell",
      "Type 1": "Grass",
      "Type 2": "Poison",
      "Total": 390,
      "HP": 65,
      "Attack": 90,
      "Defense": 50,
      "Sp. Atk": 85,
      "Sp. Def": 45,
      "Speed": 55,
   },
   "71": {
      "Name": "Victreebel",
      "Type 1": "Grass",
      "Type 2": "Poison",
      "Total": 490,
      "HP": 80,
      "Attack": 105,
      "Defense": 65,
      "Sp. Atk": 100,
      "Sp. Def": 70,
      "Speed": 70,
   },
   "72": {
      "Name": "Tentacool",
      "Type 1": "Water",
      "Type 2": "Poison",
      "Total": 335,
      "HP": 40,
      "Attack": 40,
      "Defense": 35,
      "Sp. Atk": 50,
      "Sp. Def": 100,
      "Speed": 70,
   },
   "73": {
      "Name": "Tentacruel",
      "Type 1": "Water",
      "Type 2": "Poison",
      "Total": 515,
      "HP": 80,
      "Attack": 70,
      "Defense": 65,
      "Sp. Atk": 80,
      "Sp. Def": 120,
      "Speed": 100,
   },
   "74": {
      "Name": "Geodude",
      "Type 1": "Rock",
      "Type 2": "Ground",
      "Total": 300,
      "HP": 40,
      "Attack": 80,
      "Defense": 100,
      "Sp. Atk": 30,
      "Sp. Def": 30,
      "Speed": 20,
   },
   "75": {
      "Name": "Graveler",
      "Type 1": "Rock",
      "Type 2": "Ground",
      "Total": 390,
      "HP": 55,
      "Attack": 95,
      "Defense": 115,
      "Sp. Atk": 45,
      "Sp. Def": 45,
      "Speed": 35,
   },
   "76": {
      "Name": "Golem",
      "Type 1": "Rock",
      "Type 2": "Ground",
      "Total": 495,
      "HP": 80,
      "Attack": 120,
      "Defense": 130,
      "Sp. Atk": 55,
      "Sp. Def": 65,
      "Speed": 45,
   },
   "77": {
      "Name": "Ponyta",
      "Type 1": "Fire",
      "Type 2": "",
      "Total": 410,
      "HP": 50,
      "Attack": 85,
      "Defense": 55,
      "Sp. Atk": 65,
      "Sp. Def": 65,
      "Speed": 90,
   },
   "78": {
      "Name": "Rapidash",
      "Type 1": "Fire",
      "Type 2": "",
      "Total": 500,
      "HP": 65,
      "Attack": 100,
      "Defense": 70,
      "Sp. Atk": 80,
      "Sp. Def": 80,
      "Speed": 105,
   },
   "79": {
      "Name": "Slowpoke",
      "Type 1": "Water",
      "Type 2": "Psychic",
      "Total": 315,
      "HP": 90,
      "Attack": 65,
      "Defense": 65,
      "Sp. Atk": 40,
      "Sp. Def": 40,
      "Speed": 15,
   },
   "80": {
      "Name": "Slowbro",
      "Type 1": "Water",
      "Type 2": "Psychic",
      "Total": 490,
      "HP": 95,
      "Attack": 75,
      "Defense": 110,
      "Sp. Atk": 100,
      "Sp. Def": 80,
      "Speed": 30,
   },
   "81": {
      "Name": "Magnemite",
      "Type 1": "Electric",
      "Total": 325,
      "HP": 25,
      "Attack": 35,
      "Defense": 70,
      "Sp. Atk": 95,
      "Sp. Def": 55,
      "Speed": 45,
   },
   "82": {
      "Name": "Magneton",
      "Type 1": "Electric",
      "Total": 465,
      "HP": 50,
      "Attack": 60,
      "Defense": 95,
      "Sp. Atk": 120,
      "Sp. Def": 70,
      "Speed": 70,
   },
   "83": {
      "Name": "Farfetch'd",
      "Type 1": "Normal",
      "Type 2": "Flying",
      "Total": 352,
      "HP": 52,
      "Attack": 65,
      "Defense": 55,
      "Sp. Atk": 58,
      "Sp. Def": 62,
      "Speed": 60,
   },
   "84": {
      "Name": "Doduo",
      "Type 1": "Normal",
      "Type 2": "Flying",
      "Total": 310,
      "HP": 35,
      "Attack": 85,
      "Defense": 45,
      "Sp. Atk": 35,
      "Sp. Def": 35,
      "Speed": 75,
   },
   "85": {
      "Name": "Dodrio",
      "Type 1": "Normal",
      "Type 2": "Flying",
      "Total": 460,
      "HP": 60,
      "Attack": 110,
      "Defense": 70,
      "Sp. Atk": 60,
      "Sp. Def": 60,
      "Speed": 100,
   },
   "86": {
      "Name": "Seel",
      "Type 1": "Water",
      "Type 2": "",
      "Total": 325,
      "HP": 65,
      "Attack": 45,
      "Defense": 55,
      "Sp. Atk": 45,
      "Sp. Def": 70,
      "Speed": 45,
   },
   "87": {
      "Name": "Dewgong",
      "Type 1": "Water",
      "Type 2": "Ice",
      "Total": 475,
      "HP": 90,
      "Attack": 70,
      "Defense": 80,
      "Sp. Atk": 70,
      "Sp. Def": 95,
      "Speed": 70,
   },
   "88": {
      "Name": "Grimer",
      "Type 1": "Poison",
      "Type 2": "",
      "Total": 325,
      "HP": 80,
      "Attack": 80,
      "Defense": 50,
      "Sp. Atk": 40,
      "Sp. Def": 50,
      "Speed": 25,
   },
   "89": {
      "Name": "Muk",
      "Type 1": "Poison",
      "Type 2": "",
      "Total": 500,
      "HP": 105,
      "Attack": 105,
      "Defense": 75,
      "Sp. Atk": 65,
      "Sp. Def": 100,
      "Speed": 50,
   },
   "90": {
      "Name": "Shellder",
      "Type 1": "Water",
      "Type 2": "",
      "Total": 305,
      "HP": 30,
      "Attack": 65,
      "Defense": 100,
      "Sp. Atk": 45,
      "Sp. Def": 25,
      "Speed": 40,
   },
   "91": {
      "Name": "Cloyster",
      "Type 1": "Water",
      "Type 2": "Ice",
      "Total": 525,
      "HP": 50,
      "Attack": 95,
      "Defense": 180,
      "Sp. Atk": 85,
      "Sp. Def": 45,
      "Speed": 70,
   },
   "92": {
      "Name": "Gastly",
      "Type 1": "Ghost",
      "Type 2": "Poison",
      "Total": 310,
      "HP": 30,
      "Attack": 35,
      "Defense": 30,
      "Sp. Atk": 100,
      "Sp. Def": 35,
      "Speed": 80,
   },
   "93": {
      "Name": "Haunter",
      "Type 1": "Ghost",
      "Type 2": "Poison",
      "Total": 405,
      "HP": 45,
      "Attack": 50,
      "Defense": 45,
      "Sp. Atk": 115,
      "Sp. Def": 55,
      "Speed": 95,
   },
   "94": {
      "Name": "Gengar",
      "Type 1": "Ghost",
      "Type 2": "Poison",
      "Total": 500,
      "HP": 60,
      "Attack": 65,
      "Defense": 60,
      "Sp. Atk": 130,
      "Sp. Def": 75,
      "Speed": 110,
   },
   "95": {
      "Name": "Onix",
      "Type 1": "Rock",
      "Type 2": "Ground",
      "Total": 385,
      "HP": 35,
      "Attack": 45,
      "Defense": 160,
      "Sp. Atk": 30,
      "Sp. Def": 45,
      "Speed": 70,
   },
   "96": {
      "Name": "Drowzee",
      "Type 1": "Psychic",
      "Type 2": "",
      "Total": 328,
      "HP": 60,
      "Attack": 48,
      "Defense": 45,
      "Sp. Atk": 43,
      "Sp. Def": 90,
      "Speed": 42,
   },
   "97": {
      "Name": "Hypno",
      "Type 1": "Psychic",
      "Type 2": "",
      "Total": 483,
      "HP": 85,
      "Attack": 73,
      "Defense": 70,
      "Sp. Atk": 73,
      "Sp. Def": 115,
      "Speed": 67,
   },
   "98": {
      "Name": "Krabby",
      "Type 1": "Water",
      "Type 2": "",
      "Total": 325,
      "HP": 30,
      "Attack": 105,
      "Defense": 90,
      "Sp. Atk": 25,
      "Sp. Def": 25,
      "Speed": 50,
   },
   "99": {
      "Name": "Kingler",
      "Type 1": "Water",
      "Type 2": "",
      "Total": 475,
      "HP": 55,
      "Attack": 130,
      "Defense": 115,
      "Sp. Atk": 50,
      "Sp. Def": 50,
      "Speed": 75,
   },
   "100": {
      "Name": "Voltorb",
      "Type 1": "Electric",
      "Type 2": "",
      "Total": 330,
      "HP": 40,
      "Attack": 30,
      "Defense": 50,
      "Sp. Atk": 55,
      "Sp. Def": 55,
      "Speed": 100,
   },
   "101": {
      "Name": "Electrode",
      "Type 1": "Electric",
      "Type 2": "",
      "Total": 480,
      "HP": 60,
      "Attack": 50,
      "Defense": 70,
      "Sp. Atk": 80,
      "Sp. Def": 80,
      "Speed": 140,
   },
   "102": {
      "Name": "Exeggcute",
      "Type 1": "Grass",
      "Type 2": "Psychic",
      "Total": 325,
      "HP": 60,
      "Attack": 40,
      "Defense": 80,
      "Sp. Atk": 60,
      "Sp. Def": 45,
      "Speed": 40,
   },
   "103": {
      "Name": "Exeggutor",
      "Type 1": "Grass",
      "Type 2": "Psychic",
      "Total": 520,
      "HP": 95,
      "Attack": 95,
      "Defense": 85,
      "Sp. Atk": 125,
      "Sp. Def": 65,
      "Speed": 55,
   },
   "104": {
      "Name": "Cubone",
      "Type 1": "Ground",
      "Type 2": "",
      "Total": 320,
      "HP": 50,
      "Attack": 50,
      "Defense": 95,
      "Sp. Atk": 40,
      "Sp. Def": 50,
      "Speed": 35,
   },
   "105": {
      "Name": "Marowak",
      "Type 1": "Ground",
      "Type 2": "",
      "Total": 425,
      "HP": 60,
      "Attack": 80,
      "Defense": 110,
      "Sp. Atk": 50,
      "Sp. Def": 80,
      "Speed": 45,
   },
   "106": {
      "Name": "Hitmonlee",
      "Type 1": "Fighting",
      "Type 2": "",
      "Total": 455,
      "HP": 50,
      "Attack": 120,
      "Defense": 53,
      "Sp. Atk": 35,
      "Sp. Def": 110,
      "Speed": 87,
   },
   "107": {
      "Name": "Hitmonchan",
      "Type 1": "Fighting",
      "Type 2": "",
      "Total": 455,
      "HP": 50,
      "Attack": 105,
      "Defense": 79,
      "Sp. Atk": 35,
      "Sp. Def": 110,
      "Speed": 76,
   },
   "108": {
      "Name": "Lickitung",
      "Type 1": "Normal",
      "Type 2": "",
      "Total": 385,
      "HP": 90,
      "Attack": 55,
      "Defense": 75,
      "Sp. Atk": 60,
      "Sp. Def": 75,
      "Speed": 30,
   },
   "109": {
      "Name": "Koffing",
      "Type 1": "Poison",
      "Type 2": "",
      "Total": 340,
      "HP": 40,
      "Attack": 65,
      "Defense": 95,
      "Sp. Atk": 60,
      "Sp. Def": 45,
      "Speed": 35,
   },
   "110": {
      "Name": "Weezing",
      "Type 1": "Poison",
      "Type 2": "",
      "Total": 490,
      "HP": 65,
      "Attack": 90,
      "Defense": 120,
      "Sp. Atk": 85,
      "Sp. Def": 70,
      "Speed": 60,
   },
   "111": {
      "Name": "Rhyhorn",
      "Type 1": "Ground",
      "Type 2": "Rock",
      "Total": 345,
      "HP": 80,
      "Attack": 85,
      "Defense": 95,
      "Sp. Atk": 30,
      "Sp. Def": 30,
      "Speed": 25,
   },
   "112": {
      "Name": "Rhydon",
      "Type 1": "Ground",
      "Type 2": "Rock",
      "Total": 485,
      "HP": 105,
      "Attack": 130,
      "Defense": 120,
      "Sp. Atk": 45,
      "Sp. Def": 45,
      "Speed": 40,
   },
   "113": {
      "Name": "Chansey",
      "Type 1": "Normal",
      "Type 2": "",
      "Total": 450,
      "HP": 250,
      "Attack": 5,
      "Defense": 5,
      "Sp. Atk": 35,
      "Sp. Def": 105,
      "Speed": 50,
   },
   "114": {
      "Name": "Tangela",
      "Type 1": "Grass",
      "Type 2": "",
      "Total": 435,
      "HP": 65,
      "Attack": 55,
      "Defense": 115,
      "Sp. Atk": 100,
      "Sp. Def": 40,
      "Speed": 60,
   },
   "115": {
      "Name": "Kangaskhan",
      "Type 1": "Normal",
      "Type 2": "",
      "Total": 490,
      "HP": 105,
      "Attack": 95,
      "Defense": 80,
      "Sp. Atk": 40,
      "Sp. Def": 80,
      "Speed": 90,
   },
   "116": {
      "Name": "Horsea",
      "Type 1": "Water",
      "Type 2": "",
      "Total": 295,
      "HP": 30,
      "Attack": 40,
      "Defense": 70,
      "Sp. Atk": 70,
      "Sp. Def": 25,
      "Speed": 60,
   },
   "117": {
      "Name": "Seadra",
      "Type 1": "Water",
      "Type 2": "",
      "Total": 440,
      "HP": 55,
      "Attack": 65,
      "Defense": 95,
      "Sp. Atk": 95,
      "Sp. Def": 45,
      "Speed": 85,
   },
   "118": {
      "Name": "Goldeen",
      "Type 1": "Water",
      "Type 2": "",
      "Total": 320,
      "HP": 45,
      "Attack": 67,
      "Defense": 60,
      "Sp. Atk": 35,
      "Sp. Def": 50,
      "Speed": 63,
   },
   "119": {
      "Name": "Seaking",
      "Type 1": "Water",
      "Type 2": "",
      "Total": 450,
      "HP": 80,
      "Attack": 92,
      "Defense": 65,
      "Sp. Atk": 65,
      "Sp. Def": 80,
      "Speed": 68,
   },
   "120": {
      "Name": "Staryu",
      "Type 1": "Water",
      "Type 2": "",
      "Total": 340,
      "HP": 30,
      "Attack": 45,
      "Defense": 55,
      "Sp. Atk": 70,
      "Sp. Def": 55,
      "Speed": 85,
   },
   "121": {
      "Name": "Starmie",
      "Type 1": "Water",
      "Type 2": "Psychic",
      "Total": 520,
      "HP": 60,
      "Attack": 75,
      "Defense": 85,
      "Sp. Atk": 100,
      "Sp. Def": 85,
      "Speed": 115,
   },
   "122": {
      "Name": "Mr. Mime",
      "Type 1": "Psychic",
      "Type 2": "Normal",
      "Total": 460,
      "HP": 40,
      "Attack": 45,
      "Defense": 65,
      "Sp. Atk": 100,
      "Sp. Def": 120,
      "Speed": 90,
   },
   "123": {
      "Name": "Scyther",
      "Type 1": "Bug",
      "Type 2": "Flying",
      "Total": 500,
      "HP": 70,
      "Attack": 110,
      "Defense": 80,
      "Sp. Atk": 55,
      "Sp. Def": 80,
      "Speed": 105,
   },
   "124": {
      "Name": "Jynx",
      "Type 1": "Ice",
      "Type 2": "Psychic",
      "Total": 455,
      "HP": 65,
      "Attack": 50,
      "Defense": 35,
      "Sp. Atk": 115,
      "Sp. Def": 95,
      "Speed": 95,
   },
   "125": {
      "Name": "Electabuzz",
      "Type 1": "Electric",
      "Type 2": "",
      "Total": 490,
      "HP": 65,
      "Attack": 83,
      "Defense": 57,
      "Sp. Atk": 95,
      "Sp. Def": 85,
      "Speed": 105,
   },
   "126": {
      "Name": "Magmar",
      "Type 1": "Fire",
      "Type 2": "",
      "Total": 495,
      "HP": 65,
      "Attack": 95,
      "Defense": 57,
      "Sp. Atk": 100,
      "Sp. Def": 85,
      "Speed": 93,
   },
   "127": {
      "Name": "Pinsir",
      "Type 1": "Bug",
      "Type 2": "",
      "Total": 500,
      "HP": 65,
      "Attack": 125,
      "Defense": 100,
      "Sp. Atk": 55,
      "Sp. Def": 70,
      "Speed": 85,
   },
   "128": {
      "Name": "Tauros",
      "Type 1": "Normal",
      "Type 2": "",
      "Total": 490,
      "HP": 75,
      "Attack": 100,
      "Defense": 95,
      "Sp. Atk": 40,
      "Sp. Def": 70,
      "Speed": 110,
   },
   "129": {
      "Name": "Magikarp",
      "Type 1": "Water",
      "Type 2": "",
      "Total": 200,
      "HP": 20,
      "Attack": 10,
      "Defense": 55,
      "Sp. Atk": 15,
      "Sp. Def": 20,
      "Speed": 80,
   },
   "130": {
      "Name": "Gyarados",
      "Type 1": "Water",
      "Type 2": "Flying",
      "Total": 540,
      "HP": 95,
      "Attack": 125,
      "Defense": 79,
      "Sp. Atk": 60,
      "Sp. Def": 100,
      "Speed": 81,
   },
   "131": {
      "Name": "Lapras",
      "Type 1": "Water",
      "Type 2": "Ice",
      "Total": 535,
      "HP": 130,
      "Attack": 85,
      "Defense": 80,
      "Sp. Atk": 85,
      "Sp. Def": 95,
      "Speed": 60,
   },
   "132": {
      "Name": "Ditto",
      "Type 1": "Normal",
      "Type 2": "",
      "Total": 288,
      "HP": 48,
      "Attack": 48,
      "Defense": 48,
      "Sp. Atk": 48,
      "Sp. Def": 48,
      "Speed": 48,
   },
   "133": {
      "Name": "Eevee",
      "Type 1": "Normal",
      "Type 2": "",
      "Total": 325,
      "HP": 55,
      "Attack": 55,
      "Defense": 50,
      "Sp. Atk": 45,
      "Sp. Def": 65,
      "Speed": 55,
   },
   "134": {
      "Name": "Vaporeon",
      "Type 1": "Water",
      "Type 2": "",
      "Total": 525,
      "HP": 130,
      "Attack": 65,
      "Defense": 60,
      "Sp. Atk": 110,
      "Sp. Def": 95,
      "Speed": 65,
   },
   "135": {
      "Name": "Jolteon",
      "Type 1": "Electric",
      "Type 2": "",
      "Total": 525,
      "HP": 65,
      "Attack": 65,
      "Defense": 60,
      "Sp. Atk": 110,
      "Sp. Def": 95,
      "Speed": 130,
   },
   "136": {
      "Name": "Flareon",
      "Type 1": "Fire",
      "Type 2": "",
      "Total": 525,
      "HP": 65,
      "Attack": 130,
      "Defense": 60,
      "Sp. Atk": 95,
      "Sp. Def": 110,
      "Speed": 65,
   },
   "137": {
      "Name": "Porygon",
      "Type 1": "Normal",
      "Type 2": "",
      "Total": 395,
      "HP": 65,
      "Attack": 60,
      "Defense": 70,
      "Sp. Atk": 85,
      "Sp. Def": 75,
      "Speed": 40,
   },
   "138": {
      "Name": "Omanyte",
      "Type 1": "Rock",
      "Type 2": "Water",
      "Total": 355,
      "HP": 35,
      "Attack": 40,
      "Defense": 100,
      "Sp. Atk": 90,
      "Sp. Def": 55,
      "Speed": 35,
   },
   "139": {
      "Name": "Omastar",
      "Type 1": "Rock",
      "Type 2": "Water",
      "Total": 495,
      "HP": 70,
      "Attack": 60,
      "Defense": 125,
      "Sp. Atk": 115,
      "Sp. Def": 70,
      "Speed": 55,
   },
   "140": {
      "Name": "Kabuto",
      "Type 1": "Rock",
      "Type 2": "Water",
      "Total": 355,
      "HP": 30,
      "Attack": 80,
      "Defense": 90,
      "Sp. Atk": 55,
      "Sp. Def": 45,
      "Speed": 55,
   },
   "141": {
      "Name": "Kabutops",
      "Type 1": "Rock",
      "Type 2": "Water",
      "Total": 495,
      "HP": 60,
      "Attack": 115,
      "Defense": 105,
      "Sp. Atk": 65,
      "Sp. Def": 70,
      "Speed": 80,
   },
   "142": {
      "Name": "Aerodactyl",
      "Type 1": "Rock",
      "Type 2": "Flying",
      "Total": 515,
      "HP": 80,
      "Attack": 105,
      "Defense": 65,
      "Sp. Atk": 60,
      "Sp. Def": 75,
      "Speed": 130,
   },
   "143": {
      "Name": "Snorlax",
      "Type 1": "Normal",
      "Type 2": "",
      "Total": 540,
      "HP": 160,
      "Attack": 110,
      "Defense": 65,
      "Sp. Atk": 65,
      "Sp. Def": 110,
      "Speed": 30,
   },
   "144": {
      "Name": "Articuno",
      "Type 1": "Ice",
      "Type 2": "Flying",
      "Total": 580,
      "HP": 90,
      "Attack": 85,
      "Defense": 100,
      "Sp. Atk": 95,
      "Sp. Def": 125,
      "Speed": 85,

   },
   "145": {
      "Name": "Zapdos",
      "Type 1": "Electric",
      "Type 2": "Flying",
      "Total": 580,
      "HP": 90,
      "Attack": 90,
      "Defense": 85,
      "Sp. Atk": 125,
      "Sp. Def": 90,
      "Speed": 100,

   },
   "146": {
      "Name": "Moltres",
      "Type 1": "Fire",
      "Type 2": "Flying",
      "Total": 580,
      "HP": 90,
      "Attack": 100,
      "Defense": 90,
      "Sp. Atk": 125,
      "Sp. Def": 85,
      "Speed": 90,

   },
   "147": {
      "Name": "Dratini",
      "Type 1": "Dragon",
      "Type 2": "",
      "Total": 300,
      "HP": 41,
      "Attack": 64,
      "Defense": 45,
      "Sp. Atk": 50,
      "Sp. Def": 50,
      "Speed": 50,
   },
   "148": {
      "Name": "Dragonair",
      "Type 1": "Dragon",
      "Type 2": "",
      "Total": 420,
      "HP": 61,
      "Attack": 84,
      "Defense": 65,
      "Sp. Atk": 70,
      "Sp. Def": 70,
      "Speed": 70,
   },
   "149": {
      "Name": "Dragonite",
      "Type 1": "Dragon",
      "Type 2": "Flying",
      "Total": 600,
      "HP": 91,
      "Attack": 134,
      "Defense": 95,
      "Sp. Atk": 100,
      "Sp. Def": 100,
      "Speed": 80,
   },
   "150": {
      "Name": "Mewtwo",
      "Type 1": "Psychic",
      "Type 2": "",
      "Total": 680,
      "HP": 106,
      "Attack": 110,
      "Defense": 90,
      "Sp. Atk": 154,
      "Sp. Def": 90,
      "Speed": 130,
   },
   "151": {
      "Name": "Mew",
      "Type 1": "Psychic",
      "Type 2": "",
      "Total": 600,
      "HP": 100,
      "Attack": 100,
      "Defense": 100,
      "Sp. Atk": 100,
      "Sp. Def": 100,
      "Speed": 100,
   }
}

#data on all moves
moves = {
   "1": {
      "Name": "Pound",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 35,
      "Power": "40",
      "Accuracy": "100"
   },
   "2": {
      "Name": "Karate Chop",
      "Type": "Fighting",
      "Category": "Physical",
      "PP": 25,
      "Power": "50",
      "Accuracy": "100"
   },
   "3": {
      "Name": "Double Slap",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 10,
      "Power": "15",
      "Accuracy": "85"
   },
   "4": {
      "Name": "Comet Punch",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 15,
      "Power": "18",
      "Accuracy": "85"
   },
   "5": {
      "Name": "Mega Punch",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 20,
      "Power": "80",
      "Accuracy": "85"
   },
   "6": {
      "Name": "Pay Day",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 20,
      "Power": "40",
      "Accuracy": "100"
   },
   "7": {
      "Name": "Fire Punch",
      "Type": "Fire",
      "Category": "Physical",
      "PP": 15,
      "Power": "75",
      "Accuracy": "100"
   },
   "8": {
      "Name": "Ice Punch",
      "Type": "Ice",
      "Category": "Physical",
      "PP": 15,
      "Power": "75",
      "Accuracy": "100"
   },
   "9": {
      "Name": "Thunder Punch",
      "Type": "Electric",
      "Category": "Physical",
      "PP": 15,
      "Power": "75",
      "Accuracy": "100"
   },
   "10": {
      "Name": "Scratch",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 35,
      "Power": "40",
      "Accuracy": "100"
   },
   "11": {
      "Name": "Vise Grip",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 30,
      "Power": "55",
      "Accuracy": "100"
   },
   "12": {
      "Name": "Guillotine",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 5,
      "Power": "—",
      "Accuracy": "30"
   },
   "13": {
      "Name": "Razor Wind",
      "Type": "Normal",
      "Category": "Special",
      "PP": 10,
      "Power": "80",
      "Accuracy": "100"
   },
   "14": {
      "Name": "Swords Dance",
      "Type": "Normal",
      "Category": "Status",
      "PP": 20,
      "Power": "—",
      "Accuracy": "—"
   },
   "15": {
      "Name": "Cut",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 30,
      "Power": "50",
      "Accuracy": "95"
   },
   "16": {
      "Name": "Gust",
      "Type": "Flying",
      "Category": "Special",
      "PP": 35,
      "Power": "40",
      "Accuracy": "100"
   },
   "17": {
      "Name": "Wing Attack",
      "Type": "Flying",
      "Category": "Physical",
      "PP": 35,
      "Power": "60",
      "Accuracy": "100"
   },
   "18": {
      "Name": "Whirlwind",
      "Type": "Normal",
      "Category": "Status",
      "PP": 20,
      "Power": "—",
      "Accuracy": "—"
   },
   "19": {
      "Name": "Fly",
      "Type": "Flying",
      "Category": "Physical",
      "PP": 15,
      "Power": "90",
      "Accuracy": "95"
   },
   "20": {
      "Name": "Bind",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 20,
      "Power": "15",
      "Accuracy": "85"
   },
   "21": {
      "Name": "Slam",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 20,
      "Power": "80",
      "Accuracy": "75"
   },
   "22": {
      "Name": "Vine Whip",
      "Type": "Grass",
      "Category": "Physical",
      "PP": 25,
      "Power": "45",
      "Accuracy": "100"
   },
   "23": {
      "Name": "Stomp",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 20,
      "Power": "65",
      "Accuracy": "100"
   },
   "24": {
      "Name": "Double Kick",
      "Type": "Fighting",
      "Category": "Physical",
      "PP": 30,
      "Power": "30",
      "Accuracy": "100"
   },
   "25": {
      "Name": "Mega Kick",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 5,
      "Power": "120",
      "Accuracy": "75"
   },
   "26": {
      "Name": "Jump Kick",
      "Type": "Fighting",
      "Category": "Physical",
      "PP": 10,
      "Power": "100",
      "Accuracy": "95"
   },
   "27": {
      "Name": "Rolling Kick",
      "Type": "Fighting",
      "Category": "Physical",
      "PP": 15,
      "Power": "60",
      "Accuracy": "85"
   },
   "28": {
      "Name": "Sand Attack",
      "Type": "Ground",
      "Category": "Status",
      "PP": 15,
      "Power": "—",
      "Accuracy": "100"
   },
   "29": {
      "Name": "Headbutt",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 15,
      "Power": "70",
      "Accuracy": "100"
   },
   "30": {
      "Name": "Horn Attack",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 25,
      "Power": "65",
      "Accuracy": "100"
   },
   "31": {
      "Name": "Fury Attack",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 20,
      "Power": "15",
      "Accuracy": "85"
   },
   "32": {
      "Name": "Horn Drill",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 5,
      "Power": "—",
      "Accuracy": "30"
   },
   "33": {
      "Name": "Tackle",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 35,
      "Power": "40",
      "Accuracy": "100"
   },
   "34": {
      "Name": "Body Slam",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 15,
      "Power": "85",
      "Accuracy": "100"
   },
   "35": {
      "Name": "Wrap",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 20,
      "Power": "15",
      "Accuracy": "90"
   },
   "36": {
      "Name": "Take Down",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 20,
      "Power": "90",
      "Accuracy": "85"
   },
   "37": {
      "Name": "Thrash",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 10,
      "Power": "120",
      "Accuracy": "100"
   },
   "38": {
      "Name": "Double-Edge",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 15,
      "Power": "120",
      "Accuracy": "100"
   },
   "39": {
      "Name": "Tail Whip",
      "Type": "Normal",
      "Category": "Status",
      "PP": 30,
      "Power": "—",
      "Accuracy": "100"
   },
   "40": {
      "Name": "Poison Sting",
      "Type": "Poison",
      "Category": "Physical",
      "PP": 35,
      "Power": "15",
      "Accuracy": "100"
   },
   "41": {
      "Name": "Twineedle",
      "Type": "Bug",
      "Category": "Physical",
      "PP": 20,
      "Power": "25",
      "Accuracy": "100"
   },
   "42": {
      "Name": "Pin Missile",
      "Type": "Bug",
      "Category": "Physical",
      "PP": 20,
      "Power": "25",
      "Accuracy": "95"
   },
   "43": {
      "Name": "Leer",
      "Type": "Normal",
      "Category": "Status",
      "PP": 30,
      "Power": "—",
      "Accuracy": "100"
   },
   "44": {
      "Name": "Bite",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 25,
      "Power": "60",
      "Accuracy": "100"
   },
   "45": {
      "Name": "Growl",
      "Type": "Normal",
      "Category": "Status",
      "PP": 40,
      "Power": "—",
      "Accuracy": "100"
   },
   "46": {
      "Name": "Roar",
      "Type": "Normal",
      "Category": "Status",
      "PP": 20,
      "Power": "—",
      "Accuracy": "—"
   },
   "47": {
      "Name": "Sing",
      "Type": "Normal",
      "Category": "Status",
      "PP": 15,
      "Power": "—",
      "Accuracy": "55"
   },
   "48": {
      "Name": "Supersonic",
      "Type": "Normal",
      "Category": "Status",
      "PP": 20,
      "Power": "—",
      "Accuracy": "55"
   },
   "49": {
      "Name": "Sonic Boom",
      "Type": "Normal",
      "Category": "Special",
      "PP": 20,
      "Power": "—",
      "Accuracy": "90"
   },
   "50": {
      "Name": "Disable",
      "Type": "Normal",
      "Category": "Status",
      "PP": 20,
      "Power": "—",
      "Accuracy": "100"
   },
   "51": {
      "Name": "Acid",
      "Type": "Poison",
      "Category": "Special",
      "PP": 30,
      "Power": "40",
      "Accuracy": "100"
   },
   "52": {
      "Name": "Ember",
      "Type": "Fire",
      "Category": "Special",
      "PP": 25,
      "Power": "40",
      "Accuracy": "100"
   },
   "53": {
      "Name": "Flamethrower",
      "Type": "Fire",
      "Category": "Special",
      "PP": 15,
      "Power": "90",
      "Accuracy": "100"
   },
   "54": {
      "Name": "Mist",
      "Type": "Ice",
      "Category": "Status",
      "PP": 30,
      "Power": "—",
      "Accuracy": "—"
   },
   "55": {
      "Name": "Water Gun",
      "Type": "Water",
      "Category": "Special",
      "PP": 25,
      "Power": "40",
      "Accuracy": "100"
   },
   "56": {
      "Name": "Hydro Pump",
      "Type": "Water",
      "Category": "Special",
      "PP": 5,
      "Power": "110",
      "Accuracy": "80"
   },
   "57": {
      "Name": "Surf",
      "Type": "Water",
      "Category": "Special",
      "PP": 15,
      "Power": "90",
      "Accuracy": "100"
   },
   "58": {
      "Name": "Ice Beam",
      "Type": "Ice",
      "Category": "Special",
      "PP": 10,
      "Power": "90",
      "Accuracy": "100"
   },
   "59": {
      "Name": "Blizzard",
      "Type": "Ice",
      "Category": "Special",
      "PP": 5,
      "Power": "110",
      "Accuracy": "70"
   },
   "60": {
      "Name": "Psybeam",
      "Type": "Psychic",
      "Category": "Special",
      "PP": 20,
      "Power": "65",
      "Accuracy": "100"
   },
   "61": {
      "Name": "Bubble Beam",
      "Type": "Water",
      "Category": "Special",
      "PP": 20,
      "Power": "65",
      "Accuracy": "100"
   },
   "62": {
      "Name": "Aurora Beam",
      "Type": "Ice",
      "Category": "Special",
      "PP": 20,
      "Power": "65",
      "Accuracy": "100"
   },
   "63": {
      "Name": "Hyper Beam",
      "Type": "Normal",
      "Category": "Special",
      "PP": 5,
      "Power": "150",
      "Accuracy": "90"
   },
   "64": {
      "Name": "Peck",
      "Type": "Flying",
      "Category": "Physical",
      "PP": 35,
      "Power": "35",
      "Accuracy": "100"
   },
   "65": {
      "Name": "Drill Peck",
      "Type": "Flying",
      "Category": "Physical",
      "PP": 20,
      "Power": "80",
      "Accuracy": "100"
   },
   "66": {
      "Name": "Submission",
      "Type": "Fighting",
      "Category": "Physical",
      "PP": 20,
      "Power": "80",
      "Accuracy": "80"
   },
   "67": {
      "Name": "Low Kick",
      "Type": "Fighting",
      "Category": "Physical",
      "PP": 20,
      "Power": "—",
      "Accuracy": "100"
   },
   "68": {
      "Name": "Counter",
      "Type": "Fighting",
      "Category": "Physical",
      "PP": 20,
      "Power": "—",
      "Accuracy": "100"
   },
   "69": {
      "Name": "Seismic Toss",
      "Type": "Fighting",
      "Category": "Physical",
      "PP": 20,
      "Power": "—",
      "Accuracy": "100"
   },
   "70": {
      "Name": "Strength",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 15,
      "Power": "80",
      "Accuracy": "100"
   },
   "71": {
      "Name": "Absorb",
      "Type": "Grass",
      "Category": "Special",
      "PP": 25,
      "Power": "20",
      "Accuracy": "100"
   },
   "72": {
      "Name": "Mega Drain",
      "Type": "Grass",
      "Category": "Special",
      "PP": 15,
      "Power": "40",
      "Accuracy": "100"
   },
   "73": {
      "Name": "Leech Seed",
      "Type": "Grass",
      "Category": "Status",
      "PP": 10,
      "Power": "—",
      "Accuracy": "90"
   },
   "74": {
      "Name": "Growth",
      "Type": "Normal",
      "Category": "Status",
      "PP": 20,
      "Power": "—",
      "Accuracy": "—"
   },
   "75": {
      "Name": "Razor Leaf",
      "Type": "Grass",
      "Category": "Physical",
      "PP": 25,
      "Power": "55",
      "Accuracy": "95"
   },
   "76": {
      "Name": "Solar Beam",
      "Type": "Grass",
      "Category": "Special",
      "PP": 10,
      "Power": "120",
      "Accuracy": "100"
   },
   "77": {
      "Name": "Poison Powder",
      "Type": "Poison",
      "Category": "Status",
      "PP": 35,
      "Power": "—",
      "Accuracy": "75"
   },
   "78": {
      "Name": "Stun Spore",
      "Type": "Grass",
      "Category": "Status",
      "PP": 30,
      "Power": "—",
      "Accuracy": "75"
   },
   "79": {
      "Name": "Sleep Powder",
      "Type": "Grass",
      "Category": "Status",
      "PP": 15,
      "Power": "—",
      "Accuracy": "75"
   },
   "80": {
      "Name": "Petal Dance",
      "Type": "Grass",
      "Category": "Special",
      "PP": 10,
      "Power": "120",
      "Accuracy": "100"
   },
   "81": {
      "Name": "String Shot",
      "Type": "Bug",
      "Category": "Status",
      "PP": 40,
      "Power": "—",
      "Accuracy": "95"
   },
   "82": {
      "Name": "Dragon Rage",
      "Type": "Dragon",
      "Category": "Special",
      "PP": 10,
      "Power": "—",
      "Accuracy": "100"
   },
   "83": {
      "Name": "Fire Spin",
      "Type": "Fire",
      "Category": "Special",
      "PP": 15,
      "Power": "35",
      "Accuracy": "85"
   },
   "84": {
      "Name": "Thunder Shock",
      "Type": "Electric",
      "Category": "Special",
      "PP": 30,
      "Power": "40",
      "Accuracy": "100"
   },
   "85": {
      "Name": "Thunderbolt",
      "Type": "Electric",
      "Category": "Special",
      "PP": 15,
      "Power": "90",
      "Accuracy": "100"
   },
   "86": {
      "Name": "Thunder Wave",
      "Type": "Electric",
      "Category": "Status",
      "PP": 20,
      "Power": "—",
      "Accuracy": "90"
   },
   "87": {
      "Name": "Thunder",
      "Type": "Electric",
      "Category": "Special",
      "PP": 10,
      "Power": "110",
      "Accuracy": "70"
   },
   "88": {
      "Name": "Rock Throw",
      "Type": "Rock",
      "Category": "Physical",
      "PP": 15,
      "Power": "50",
      "Accuracy": "90"
   },
   "89": {
      "Name": "Earthquake",
      "Type": "Ground",
      "Category": "Physical",
      "PP": 10,
      "Power": "100",
      "Accuracy": "100"
   },
   "90": {
      "Name": "Fissure",
      "Type": "Ground",
      "Category": "Physical",
      "PP": 5,
      "Power": "—",
      "Accuracy": "30"
   },
   "91": {
      "Name": "Dig",
      "Type": "Ground",
      "Category": "Physical",
      "PP": 10,
      "Power": "80",
      "Accuracy": "100"
   },
   "92": {
      "Name": "Toxic",
      "Type": "Poison",
      "Category": "Status",
      "PP": 10,
      "Power": "—",
      "Accuracy": "90"
   },
   "93": {
      "Name": "Confusion",
      "Type": "Psychic",
      "Category": "Special",
      "PP": 25,
      "Power": "50",
      "Accuracy": "100"
   },
   "94": {
      "Name": "Psychic",
      "Type": "Psychic",
      "Category": "Special",
      "PP": 10,
      "Power": "90",
      "Accuracy": "100"
   },
   "95": {
      "Name": "Hypnosis",
      "Type": "Psychic",
      "Category": "Status",
      "PP": 20,
      "Power": "—",
      "Accuracy": "60"
   },
   "96": {
      "Name": "Meditate",
      "Type": "Psychic",
      "Category": "Status",
      "PP": 40,
      "Power": "—",
      "Accuracy": "—"
   },
   "97": {
      "Name": "Agility",
      "Type": "Psychic",
      "Category": "Status",
      "PP": 30,
      "Power": "—",
      "Accuracy": "—"
   },
   "98": {
      "Name": "Quick Attack",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 30,
      "Power": "40",
      "Accuracy": "100"
   },
   "99": {
      "Name": "Rage",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 20,
      "Power": "20",
      "Accuracy": "100"
   },
   "100": {
      "Name": "Teleport",
      "Type": "Psychic",
      "Category": "Status",
      "PP": 20,
      "Power": "—",
      "Accuracy": "—"
   },
   "101": {
      "Name": "Night Shade",
      "Type": "Ghost",
      "Category": "Special",
      "PP": 15,
      "Power": "—",
      "Accuracy": "100"
   },
   "102": {
      "Name": "Mimic",
      "Type": "Normal",
      "Category": "Status",
      "PP": 10,
      "Power": "—",
      "Accuracy": "—"
   },
   "103": {
      "Name": "Screech",
      "Type": "Normal",
      "Category": "Status",
      "PP": 40,
      "Power": "—",
      "Accuracy": "85"
   },
   "104": {
      "Name": "Double Team",
      "Type": "Normal",
      "Category": "Status",
      "PP": 15,
      "Power": "—",
      "Accuracy": "—"
   },
   "105": {
      "Name": "Recover",
      "Type": "Normal",
      "Category": "Status",
      "PP": 5,
      "Power": "—",
      "Accuracy": "—"
   },
   "106": {
      "Name": "Harden",
      "Type": "Normal",
      "Category": "Status",
      "PP": 30,
      "Power": "—",
      "Accuracy": "—"
   },
   "107": {
      "Name": "Minimize",
      "Type": "Normal",
      "Category": "Status",
      "PP": 10,
      "Power": "—",
      "Accuracy": "—"
   },
   "108": {
      "Name": "Smokescreen",
      "Type": "Normal",
      "Category": "Status",
      "PP": 20,
      "Power": "—",
      "Accuracy": "100"
   },
   "109": {
      "Name": "Confuse Ray",
      "Type": "Ghost",
      "Category": "Status",
      "PP": 10,
      "Power": "—",
      "Accuracy": "100"
   },
   "110": {
      "Name": "Withdraw",
      "Type": "Water",
      "Category": "Status",
      "PP": 40,
      "Power": "—",
      "Accuracy": "—"
   },
   "111": {
      "Name": "Defense Curl",
      "Type": "Normal",
      "Category": "Status",
      "PP": 40,
      "Power": "—",
      "Accuracy": "—"
   },
   "112": {
      "Name": "Barrier",
      "Type": "Psychic",
      "Category": "Status",
      "PP": 20,
      "Power": "—",
      "Accuracy": "—"
   },
   "113": {
      "Name": "Light Screen",
      "Type": "Psychic",
      "Category": "Status",
      "PP": 30,
      "Power": "—",
      "Accuracy": "—"
   },
   "114": {
      "Name": "Haze",
      "Type": "Ice",
      "Category": "Status",
      "PP": 30,
      "Power": "—",
      "Accuracy": "—"
   },
   "115": {
      "Name": "Reflect",
      "Type": "Psychic",
      "Category": "Status",
      "PP": 20,
      "Power": "—",
      "Accuracy": "—"
   },
   "116": {
      "Name": "Focus Energy",
      "Type": "Normal",
      "Category": "Status",
      "PP": 30,
      "Power": "—",
      "Accuracy": "—"
   },
   "117": {
      "Name": "Bide",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 10,
      "Power": "—",
      "Accuracy": "—"
   },
   "118": {
      "Name": "Metronome",
      "Type": "Normal",
      "Category": "Status",
      "PP": 10,
      "Power": "—",
      "Accuracy": "—"
   },
   "119": {
      "Name": "Mirror Move",
      "Type": "Flying",
      "Category": "Status",
      "PP": 20,
      "Power": "—",
      "Accuracy": "—"
   },
   "120": {
      "Name": "Self-Destruct",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 5,
      "Power": "200",
      "Accuracy": "100"
   },
   "121": {
      "Name": "Egg Bomb",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 10,
      "Power": "100",
      "Accuracy": "75"
   },
   "122": {
      "Name": "Lick",
      "Type": "Ghost",
      "Category": "Physical",
      "PP": 30,
      "Power": "30",
      "Accuracy": "100"
   },
   "123": {
      "Name": "Smog",
      "Type": "Poison",
      "Category": "Special",
      "PP": 20,
      "Power": "30",
      "Accuracy": "70"
   },
   "124": {
      "Name": "Sludge",
      "Type": "Poison",
      "Category": "Special",
      "PP": 20,
      "Power": "65",
      "Accuracy": "100"
   },
   "125": {
      "Name": "Bone Club",
      "Type": "Ground",
      "Category": "Physical",
      "PP": 20,
      "Power": "65",
      "Accuracy": "85"
   },
   "126": {
      "Name": "Fire Blast",
      "Type": "Fire",
      "Category": "Special",
      "PP": 5,
      "Power": "110",
      "Accuracy": "85"
   },
   "127": {
      "Name": "Waterfall",
      "Type": "Water",
      "Category": "Physical",
      "PP": 15,
      "Power": "80",
      "Accuracy": "100"
   },
   "128": {
      "Name": "Clamp",
      "Type": "Water",
      "Category": "Physical",
      "PP": 15,
      "Power": "35",
      "Accuracy": "85"
   },
   "129": {
      "Name": "Swift",
      "Type": "Normal",
      "Category": "Special",
      "PP": 20,
      "Power": "60",
      "Accuracy": "—"
   },
   "130": {
      "Name": "Skull Bash",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 10,
      "Power": "130",
      "Accuracy": "100"
   },
   "131": {
      "Name": "Spike Cannon",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 15,
      "Power": "20",
      "Accuracy": "100"
   },
   "132": {
      "Name": "Constrict",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 35,
      "Power": "10",
      "Accuracy": "100"
   },
   "133": {
      "Name": "Amnesia",
      "Type": "Psychic",
      "Category": "Status",
      "PP": 20,
      "Power": "—",
      "Accuracy": "—"
   },
   "134": {
      "Name": "Kinesis",
      "Type": "Psychic",
      "Category": "Status",
      "PP": 15,
      "Power": "—",
      "Accuracy": "80"
   },
   "135": {
      "Name": "Soft-Boiled",
      "Type": "Normal",
      "Category": "Status",
      "PP": 5,
      "Power": "—",
      "Accuracy": "—"
   },
   "136": {
      "Name": "High Jump Kick",
      "Type": "Fighting",
      "Category": "Physical",
      "PP": 10,
      "Power": "130",
      "Accuracy": "90"
   },
   "137": {
      "Name": "Glare",
      "Type": "Normal",
      "Category": "Status",
      "PP": 30,
      "Power": "—",
      "Accuracy": "100"
   },
   "138": {
      "Name": "Dream Eater",
      "Type": "Psychic",
      "Category": "Special",
      "PP": 15,
      "Power": "100",
      "Accuracy": "100"
   },
   "139": {
      "Name": "Poison Gas",
      "Type": "Poison",
      "Category": "Status",
      "PP": 40,
      "Power": "—",
      "Accuracy": "90"
   },
   "140": {
      "Name": "Barrage",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 20,
      "Power": "15",
      "Accuracy": "85"
   },
   "141": {
      "Name": "Leech Life",
      "Type": "Bug",
      "Category": "Physical",
      "PP": 10,
      "Power": "80",
      "Accuracy": "100"
   },
   "142": {
      "Name": "Lovely Kiss",
      "Type": "Normal",
      "Category": "Status",
      "PP": 10,
      "Power": "—",
      "Accuracy": "75"
   },
   "143": {
      "Name": "Sky Attack",
      "Type": "Flying",
      "Category": "Physical",
      "PP": 5,
      "Power": "140",
      "Accuracy": "90"
   },
   "144": {
      "Name": "Transform",
      "Type": "Normal",
      "Category": "Status",
      "PP": 10,
      "Power": "—",
      "Accuracy": "—"
   },
   "145": {
      "Name": "Bubble",
      "Type": "Water",
      "Category": "Special",
      "PP": 30,
      "Power": "40",
      "Accuracy": "100"
   },
   "146": {
      "Name": "Dizzy Punch",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 10,
      "Power": "70",
      "Accuracy": "100"
   },
   "147": {
      "Name": "Spore",
      "Type": "Grass",
      "Category": "Status",
      "PP": 15,
      "Power": "—",
      "Accuracy": "100"
   },
   "148": {
      "Name": "Flash",
      "Type": "Normal",
      "Category": "Status",
      "PP": 20,
      "Power": "—",
      "Accuracy": "100"
   },
   "149": {
      "Name": "Psywave",
      "Type": "Psychic",
      "Category": "Special",
      "PP": 15,
      "Power": "—",
      "Accuracy": "100"
   },
   "150": {
      "Name": "Splash",
      "Type": "Normal",
      "Category": "Status",
      "PP": 40,
      "Power": "—",
      "Accuracy": "—"
   },
   "151": {
      "Name": "Acid Armor",
      "Type": "Poison",
      "Category": "Status",
      "PP": 20,
      "Power": "—",
      "Accuracy": "—"
   },
   "152": {
      "Name": "Crabhammer",
      "Type": "Water",
      "Category": "Physical",
      "PP": 10,
      "Power": "100",
      "Accuracy": "90"
   },
   "153": {
      "Name": "Explosion",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 5,
      "Power": "250",
      "Accuracy": "100"
   },
   "154": {
      "Name": "Fury Swipes",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 15,
      "Power": "18",
      "Accuracy": "80"
   },
   "155": {
      "Name": "Bonemerang",
      "Type": "Ground",
      "Category": "Physical",
      "PP": 10,
      "Power": "50",
      "Accuracy": "90"
   },
   "156": {
      "Name": "Rest",
      "Type": "Psychic",
      "Category": "Status",
      "PP": 5,
      "Power": "—",
      "Accuracy": "—"
   },
   "157": {
      "Name": "Rock Slide",
      "Type": "Rock",
      "Category": "Physical",
      "PP": 10,
      "Power": "75",
      "Accuracy": "90"
   },
   "158": {
      "Name": "Hyper Fang",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 15,
      "Power": "80",
      "Accuracy": "90"
   },
   "159": {
      "Name": "Sharpen",
      "Type": "Normal",
      "Category": "Status",
      "PP": 30,
      "Power": "—",
      "Accuracy": "—"
   },
   "160": {
      "Name": "Conversion",
      "Type": "Normal",
      "Category": "Status",
      "PP": 30,
      "Power": "—",
      "Accuracy": "—"
   },
   "161": {
      "Name": "Tri Attack",
      "Type": "Normal",
      "Category": "Special",
      "PP": 10,
      "Power": "80",
      "Accuracy": "100"
   },
   "162": {
      "Name": "Super Fang",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 10,
      "Power": "—",
      "Accuracy": "90"
   },
   "163": {
      "Name": "Slash",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 20,
      "Power": "70",
      "Accuracy": "100"
   },
   "164": {
      "Name": "Substitute",
      "Type": "Normal",
      "Category": "Status",
      "PP": 10,
      "Power": "—",
      "Accuracy": "—"
   },
   "165": {
      "Name": "Struggle",
      "Type": "Normal",
      "Category": "Physical",
      "PP": 1,
      "Power": "50",
      "Accuracy": "—"
   }
}
